version: '3.8'

services:
  app:
    image: your-spring-app
    environment:
      - DOCKER_ENV=true
      - DB_URL=jdbc:mysql://mysql:3306/your_db
      - DB_USERNAME=root
      - DB_PASSWORD=shoko
    depends_on:
      - mysql
    ports:
      - "8080:8080"  # If your app exposes port 8080 (adjust as needed)

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=shoko
      - MYSQL_DATABASE=your_db
    ports:
      - "3306:3306"

